# Generated by Django 5.0.6 on 2024-07-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnimalType',
            new_name='Type',
        ),
    ]
